import { describe, expect, it } from 'vitest';
import { mutlakYollariGizle, type RaporSayimlari, type RaporTesti } from '../../src/rapor/html.js';
import {
  OZET_ISARETI, OZET_SINIRI, duzeltmeIstemi, hepsiniDuzeltIstemi, metniTemizle, ozetMarkdown, type OzetGirdisi,
} from '../../src/rapor/index.js';

const kokler = [{ yol: '/Users/alice/shop', yerTutucu: '[project]' }];
const temizle = (metin: string): string => metniTemizle(metin, kokler);
const baglam = { baseUrl: 'http://localhost:3000', temizle };

function test_(no: number, ek: Partial<RaporTesti> = {}): RaporTesti {
  return {
    id: `t_aaaaaa${String(no).padStart(2, '0')}`,
    name: `Save record ${no}`,
    priority: 'p1',
    verdict: 'failed',
    runId: 'r_20261005100000_aaaa',
    failureKind: 'unknown',
    errorMessage: 'expect(locator).toBeVisible() failed',
    steps: [{ index: 0, description: 'Open the page', type: 'action', status: 'failed' }],
    ...ek,
  };
}

function sayim(testler: readonly RaporTesti[]): RaporSayimlari {
  const c: RaporSayimlari = { passed: 0, failed: 0, blocked: 0, inconclusive: 0, notRun: 0 };
  for (const t of testler) {
    if (t.verdict === 'not_run') c.notRun += 1;
    else c[t.verdict] += 1;
  }
  return c;
}

/** Rapor katmanının yaptığı gibi: istemler değer değer temizlenmiş üretilir. */
function girdi(testler: RaporTesti[], ek: Partial<OzetGirdisi> = {}): OzetGirdisi {
  const dikkat = testler.filter((t) => t.verdict === 'failed' || t.verdict === 'blocked' || t.verdict === 'inconclusive');
  const hepsi = hepsiniDuzeltIstemi(testler, baglam);
  return {
    testler,
    counts: sayim(testler),
    surum: '0.2.1',
    fixPrompts: dikkat.map((t) => ({ id: t.id, prompt: duzeltmeIstemi(t, baglam) })),
    ...(hepsi === null ? {} : { fixAllPrompt: hepsi }),
    temizle,
    ...ek,
  };
}

/** `<details>` blokları: özet satırı ve dış çitin içeriği; dış çit kapanmadan blok bitmez. */
function detaylar(md: string): Array<{ ozet: string; icerik: string }> {
  const satirlar = md.split('\n');
  const sonuc: Array<{ ozet: string; icerik: string }> = [];
  for (let i = 0; i < satirlar.length; i += 1) {
    if (satirlar[i] !== '<details>') continue;
    const ozet = satirlar[i + 1] ?? '';
    expect(satirlar[i + 2]).toBe('');
    const acilis = satirlar[i + 3] ?? '';
    const cit = /^(`{3,})text$/.exec(acilis)?.[1];
    expect(cit, acilis).toBeDefined();
    // Kapanış: açılışla AYNI uzunlukta tek başına çit satırı (CommonMark'ta daha kısa çit kapatamaz).
    let j = i + 4;
    while (j < satirlar.length && satirlar[j] !== cit) j += 1;
    expect(j).toBeLessThan(satirlar.length);
    expect(satirlar[j + 1]).toBe('');
    expect(satirlar[j + 2]).toBe('</details>');
    sonuc.push({ ozet, icerik: satirlar.slice(i + 4, j).join('\n') });
    i = j + 2;
  }
  return sonuc;
}

describe('ozetMarkdown (kobay test report --summary)', () => {
  it('starts with the sticky marker, then the heading, counts table and test table, and ends with the footer', () => {
    const testler = [test_(1, { verdict: 'passed', failureKind: undefined }), test_(2), test_(3, { verdict: 'not_run', failureKind: undefined, runId: undefined })];
    const md = ozetMarkdown(girdi(testler));
    const satirlar = md.split('\n');
    expect(satirlar[0]).toBe(OZET_ISARETI);
    expect(satirlar[1]).toBe('## kobay test report');
    expect(md).toContain('| passed | failed | blocked | inconclusive | not run |\n|---:|---:|---:|---:|---:|\n| 1 | 1 | 0 | 0 | 1 |');
    expect(md).toContain('| ID | Name | Verdict | Failure kind |');
    expect(md).toContain('| t\\_aaaaaa01 | Save record 1 | passed | - |');
    expect(md).toContain('| t\\_aaaaaa02 | Save record 2 | failed | unknown |');
    expect(md).toContain('| t\\_aaaaaa03 | Save record 3 | not run | - |');
    expect(md).toContain('**1 of 3 tests needs attention.**');
    expect(md.trimEnd().split('\n').at(-1)).toMatch(/^Generated by kobay 0\.2\.1\. .*report artifact/);
    // Tek dikkat gereken test: bir istem, hepsini düzelt istemi yok.
    const bloklar = detaylar(md);
    expect(bloklar.map((b) => b.ozet)).toEqual(['<summary>Fix with your coding agent — t_aaaaaa02 Save record 2</summary>']);
    expect(bloklar[0]?.icerik).toBe(duzeltmeIstemi(testler[1]!, baglam));
  });

  it('adds a separate fix-all block for two or more tests that need attention', () => {
    const testler = [test_(1), test_(2, { verdict: 'blocked', failureKind: undefined })];
    const md = ozetMarkdown(girdi(testler));
    const bloklar = detaylar(md);
    expect(bloklar).toHaveLength(3);
    expect(bloklar[2]?.ozet).toBe('<summary>Fix all 2 tests that need attention with your coding agent</summary>');
    expect(bloklar[2]?.icerik).toBe(hepsiniDuzeltIstemi(testler, baglam));
  });

  it('shows at most --max-prompts prompts and one line for the rest', () => {
    const testler = Array.from({ length: 7 }, (_d, i) => test_(i + 1));
    const md = ozetMarkdown(girdi(testler));
    // 5 tekil + 1 hepsini düzelt.
    expect(detaylar(md)).toHaveLength(6);
    expect(md).toContain('2 more failing tests — see the report artifact.');

    const iki = ozetMarkdown(girdi(testler, { maxIstem: 2 }));
    expect(detaylar(iki).map((b) => b.ozet).filter((o) => o.includes('Fix with your coding agent'))).toHaveLength(2);
    expect(iki).toContain('5 more failing tests — see the report artifact.');

    const sifir = ozetMarkdown(girdi(testler.slice(0, 2), { maxIstem: 0 }));
    expect(sifir).toContain('2 more failing tests — see the report artifact.');
    expect(detaylar(sifir).map((b) => b.ozet)).toEqual(['<summary>Fix all 2 tests that need attention with your coding agent</summary>']);
  });

  it('stays within the size limit: drops fix-all first, then prompts from the end, never the table', () => {
    const uzun = 'x'.repeat(1900);
    const testler = Array.from({ length: 30 }, (_d, i) => test_(i + 1, { errorMessage: `${uzun} ${i}` }));
    const tam = ozetMarkdown(girdi(testler, { maxIstem: 30, sinir: 10_000_000 }));
    expect(tam.length).toBeGreaterThan(OZET_SINIRI);

    const md = ozetMarkdown(girdi(testler, { maxIstem: 30 }));
    expect(md.length).toBeLessThanOrEqual(OZET_SINIRI);
    expect(md).toContain('truncated');
    expect(md).not.toContain('Fix all 30 tests');
    const tekil = detaylar(md).map((b) => b.ozet);
    expect(tekil.length).toBeGreaterThan(0);
    expect(tekil.length).toBeLessThan(30);
    // Sondan düşer: kalanlar baştakiler.
    expect(tekil.at(-1)).toContain(`t_aaaaaa${String(tekil.length).padStart(2, '0')}`);
    expect(md).toContain(`${30 - tekil.length} more failing tests — see the report artifact.`);
    for (const t of testler) expect(md).toContain(`| ${t.id.replace('_', '\\_')} | ${t.name} | failed | unknown |`);

    // Daha küçük sınır: fixAll düşer ama istemler sığarsa kalır.
    const kucuk = ozetMarkdown(girdi(testler.slice(0, 2), { sinir: 9_500 }));
    expect(kucuk.length).toBeLessThanOrEqual(9_500);
    expect(kucuk).not.toContain('Fix all 2 tests');
    expect(detaylar(kucuk)).toHaveLength(2);
  });

  it('a table too long on its own: names shrink first, then rows are cut with an explicit note, in linear-ish time', () => {
    const uzunAd = 'N'.repeat(200);
    const orta = Array.from({ length: 500 }, (_d, i) => test_(i, { id: `t_${String(i).padStart(8, '0')}`, name: `${uzunAd} ${i}`, verdict: 'passed', failureKind: undefined }));
    const md1 = ozetMarkdown(girdi(orta));
    expect(md1.length).toBeLessThanOrEqual(OZET_SINIRI);
    expect(md1).not.toContain('Table truncated');
    expect(md1.match(/^\| t\\_/gm)).toHaveLength(500);

    const cok = Array.from({ length: 3000 }, (_d, i) => test_(i, { id: `t_${String(i).padStart(8, '0')}`, name: `${uzunAd} ${i}` }));
    const bas = Date.now();
    const md2 = ozetMarkdown(girdi(cok));
    expect(Date.now() - bas).toBeLessThan(5_000);
    expect(md2.length).toBeLessThanOrEqual(OZET_SINIRI);
    const satir = md2.match(/^\| t\\_/gm)?.length ?? 0;
    expect(satir).toBeGreaterThan(100);
    expect(md2).toContain(`Table truncated: ${3000 - satir} rows omitted — see the report artifact.`);
    expect(md2).toContain('| 0 | 3000 | 0 | 0 | 0 |');
  });

  it('masks secrets and replaces local paths in the test name and in the prompts', () => {
    const testler = [
      test_(1, { name: 'Login password: hunter22', errorMessage: 'Body {"password": "s3cretValue9"} at /Users/alice/shop/app.ts' }),
      test_(2),
    ];
    const md = ozetMarkdown(girdi(testler));
    expect(md).not.toContain('hunter22');
    expect(md).not.toContain('s3cretValue9');
    expect(md).not.toContain('/Users/alice');
    expect(md).toContain('[redacted]');
    expect(md).toContain('[project]/app.ts');
  });

  it('escapes table cells: pipes, angle brackets, Markdown links and line breaks', () => {
    const ad = 'A | B <img src=x onerror=alert(1)> [click](https://evil.test) **bold**\nsecond line';
    const md = ozetMarkdown(girdi([test_(1, { name: ad, verdict: 'passed', failureKind: undefined })]));
    const satir = md.split('\n').find((s) => s.startsWith('| t\\_aaaaaa01'));
    expect(satir).toBe(
      '| t\\_aaaaaa01 | A \\| B &lt;img src=x onerror=alert\\(1\\)&gt; \\[click\\]\\(https://evil.test\\) \\*\\*bold\\*\\* second line | passed | - |',
    );
    // Satırda kaçışsız tek `|` hücre sınırından başka yerde yok: 5 sınır.
    expect(satir?.replace(/\\\|/g, '').split('|')).toHaveLength(6);
    expect(md).not.toContain('<img');
  });

  it('an attempt to break out of the code fence or the details block stays inside the block', () => {
    const kacis = 'done\n```\n</details>\n<img src=x onerror=alert(1)>\n````\n# Injected heading';
    const testler = [test_(1, { name: 'Name </summary><b>x</b>', errorMessage: kacis }), test_(2)];
    const md = ozetMarkdown(girdi(testler));
    const bloklar = detaylar(md);
    expect(bloklar).toHaveLength(3);
    expect(bloklar[0]?.ozet).toBe('<summary>Fix with your coding agent — t_aaaaaa01 Name &lt;/summary&gt;&lt;b&gt;x&lt;/b&gt;</summary>');
    expect(bloklar[0]?.icerik).toBe(duzeltmeIstemi(testler[0]!, baglam));
    expect(bloklar[0]?.icerik).toContain('# Injected heading');
    // Saldırgan metni yalnız çitli blokların içinde geçer.
    const disari = md.split('\n').filter((s) => s === '# Injected heading' || s === '</details>');
    expect(disari.filter((s) => s === '</details>')).toHaveLength(3 + 2);
  });
});

describe('mutlakYollariGizle (summary path masking)', () => {
  it.each([
    ['cwd:/opt/private/file.ts:1:2', 'cwd:[path]/file.ts:1:2'],
    ['at /data/app/x.js:1', 'at [path]/x.js:1'],
    ['at /azp/_work/1/s/x.ts', 'at [path]/x.ts'],
    ['at /srv/app/x.ts', 'at [path]/x.ts'],
    ['at /mnt/disk/x.ts', 'at [path]/x.ts'],
    ['at /workspace/repo/x.ts', 'at [path]/x.ts'],
    ['at /github/workspace/x.ts', 'at [path]/x.ts'],
    ['at /runner/_work/x.ts', 'at [path]/x.ts'],
    ['at /builds/group/x.ts', 'at [path]/x.ts'],
    ['at /root/app/x.ts', 'at [path]/x.ts'],
    ['at /w/repo/x.ts', 'at [path]/x.ts'],
    ['at /__w/repo/repo/x.ts', 'at [path]/x.ts'],
    ['file:///opt/a/b', 'file://[path]/b'],
    ['(C:\\Users\\bob\\x.ts:3:4)', '([path]/x.ts:3:4)'],
    // URL'ler ve sıradan rotalar korunur.
    ['see https://host.test/opt/x/y', 'see https://host.test/opt/x/y'],
    ['see http://localhost:3000/data/x', 'see http://localhost:3000/data/x'],
    ['https://opt/x/y', 'https://opt/x/y'],
    ['Expected URL /records/new', 'Expected URL /records/new'],
    ['key:value /api/users/1', 'key:value /api/users/1'],
    // Kabul edilen ödünleşim: sistem kökü adıyla başlayan rota da maskelenir.
    ['Expected URL /opt/x', 'Expected URL [path]/x'],
  ])('%s', (girdi, beklenen) => {
    expect(mutlakYollariGizle(girdi)).toBe(beklenen);
  });
});
